server:
  applicationConnectors:
    - type: http
      port: 0
  adminConnectors:
    - type: http
      port: 0
# metrics
metrics:
  frequency: 1 minute
  reporters:
    - type: console
      output: stdout
      timeZone: PST
      durationUnit: milliseconds
      rateUnit: seconds

traceHeaders:
  headersToTraceJson: "{\"x-custom-header\": [\"x-custom-header-value1\", \"x-custom-header-value2\"], \"y-custom-header\": \"y-custom-header-value1\"}"
  metricPrefix: HeaderMetric
