server:
  applicationConnectors:
    - type: http
      port: 0
  adminConnectors:
    - type: http
      port: 0
# metrics
metrics:
  frequency: 1 minute
  reporters:
    - type: console
      output: stdout
      timeZone: PST
      durationUnit: milliseconds
      rateUnit: seconds